language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t wmayur19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wmayur19/docker-react npm run test
